FROM python:3.9

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY . /api

ENV MYSQL_HOST=? MYSQL_PORT=3306 \ 
    MYSQL_USER=? MYSQL_PASSWORD=? MYSQL_DATABASE=?

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

